version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: blinkit_postgres
    environment:
      POSTGRES_USER: blinkit_user
      POSTGRES_PASSWORD: blinkit_password
      POSTGRES_DB: blinkit_discovery
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

  redis:
    image: redis:7
    container_name: blinkit_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
